# Setup
title:               Yanci's blog
tagline:             ''
description:         'Deep Learning, computational neural science, biomedical engineering, economics.'
url:                 http://ytliang97.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Yanci Liang
  url:               null
  email:             ytliang97@gmail.com

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
